#ifndef LETT_LANG_LETT_H
#define LETT_LANG_LETT_H

#define LETT_LANG_STR(x) #x
#define LETT_LANG_STR_X(x) LETT_LANG_STR(x)

#define LETT_LANG_MAJOR 0
#define LETT_LANG_MINOR 0
#define LETT_LANG_PATCH 1

#define LETT_LANG_VERSION LETT_LANG_STR_X(LETT_LANG_MAJOR) "." LETT_LANG_STR_X(LETT_LANG_MINOR) "." LETT_LANG_STR_X(LETT_LANG_PATCH)

#include "lexer.h"

#endif //LETT_LANG_LETT_H
